// message types
const types = {
    ALARM_UPDATE: 'ALARM_UPDATE',
    READ_POST: 'READ_POST',
    READ_POSTS: 'READ_POSTS',
    READ_ALL: 'READ_ALL',
    NEW_POSTS: 'NEW_POSTS',
    NEW_MESSAGES: 'NEW_MESSAGES',
    RESET: 'RESET',
    UPDATE_NOW: 'UPDATE_NOW',
    UPDATING_START: 'UPDATING_START',
    UPDATING_END: 'UPDATING_END',
    START_AUTH_FLOW: 'START_AUTH_FLOW',
    SCHEDULE_NEXT_UPDATE: 'SCHEDULE_NEXT_UPDATE',
};

export default types;
