// message types
const types = {
    ALARM_UPDATE: 'ALARM_UPDATE',
    UPDATE_NOW: 'UPDATE_NOW',
    UPDATING_START: 'UPDATING_START',
    UPDATING_END: 'UPDATING_END',
    SCHEDULE_NEXT_UPDATE: 'SCHEDULE_NEXT_UPDATE',
};

export default types;
